{
    vertexShaderFile:"vertex.glsl",
    fragmentShaderFile:"fragment.glsl",
    meshes:[
        {
            type:"plane",
            name:"Ocean",
            rx:-90,
            subdivision:128,
            scale:1.5
        }
    ],
    animated:true,
    autoOrbit:true,
    zoom:true,
    cameraDistance:75
}
